# Train Configuration

# Train & Test Parameters
train:
  model_dir: model
  model_type: wide_deep
  train_data: data/criteo/train.csv
  dev_data: data/criteo/dev.csv
  test_data: data/criteo/test.csv
  batch_size: 256
  train_epochs: 5
  epochs_per_eval: 1
  keep_train: 0
  num_samples: 50000000
  checkpoint_path:

# Model Parameters
model:
  # wide
  wide_learning_rate: 0.1
  wide_lr_decay: true
  wide_l1: 0.5
  wide_l2: 1
  # deep
  hidden_units: [1024, 512, 256]
  connect_mode: normal
  residual_mode:

  deep_learning_rate: 0.1
  deep_lr_decay: false
  activation_function: tf.nn.relu
  deep_l1: 0.01
  deep_l2: 0.01
  dropout:
  batch_normalization: false

# Saving Parameters (Optional)
runconfig:
  tf_random_seed: 12345
  save_summary_steps: 100
  save_checkpoints_steps:
  save_checkpoints_secs: 1500
  keep_checkpoint_max: 5
  keep_checkpoint_every_n_hours: 1
  log_step_count_steps: 100

# Distributed Parameters
distributed:
  is_distributed: 0
  cluster:
    ps: ['10.172.110.162:3333']
    chief: ['10.120.180.212:3333']
    worker: ['10.120.180.213:3333', '10.120.180.213:3333', '10.120.180.214:3333', '10.120.180.215:3333']
  job_name: ps
  task_index: 0









